version: "3.4"

services:
  app:
    container_name: nodejs_container
    restart: always
    build: .
    ports:
      - "9000:9000"
    links:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
